name: Cross-Build

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'master-cmake'
      - '!**4.3'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./tools/build.sh ${{ matrix.target }} DISPLAY=1
